// ===============================
// Admin Command and Response
// ===============================
/** @type {AdminConfig} */
const _adminConfig = {
	commands: {
		timer: ['!timer', '!pomo'],
		clearList: ['!clearlist'],
		clearDone: ['!cleardone'],
		clearUser: ['!clearuser'],
		pause: ['!pause'],
		resume: ['!resume'],
	},
	responseTo: {
		EN: {
			timer: 'Focus timer set to {message} minutes',
			pomo: 'Pomodoro session {session}/{total} started! Focus for {duration} minutes 🍅',
			pomoBreak: 'Session {session}/{total} complete! Time for a {break} minute break ☕',
			pomoComplete: 'All {total} Pomodoro sessions complete! Great work! 🎉',
			pause: 'Timer paused ⏸️',
			resume: 'Timer resumed ▶️',
			clearList: 'All tasks have been cleared',
			clearDone: 'All done tasks have been cleared',
			clearUser: 'All tasks for {message} have been cleared',
		},
		ES: {
			timer: 'El temporizador se ha restablecido a {message} minutos',
			pomo: '¡Sesión Pomodoro {session}/{total} iniciada! Concéntrate durante {duration} minutos 🍅',
			pomoBreak: '¡Sesión {session}/{total} completada! Toma un descanso de {break} minutos ☕',
			pomoComplete: '¡Las {total} sesiones Pomodoro están completas! ¡Buen trabajo! 🎉',
			pause: 'Temporizador en pausa ⏸️',
			resume: 'Temporizador reanudado ▶️',
			clearList: 'Todas las tareas han sido eliminadas',
			clearDone: 'Todas las tareas completadas han sido eliminadas',
			clearUser: 'Todas las tareas de {message} han sido eliminadas',
		},
		FR: {
			timer: 'Minuteur réglé à {message} minutes',
			pomo: 'Session Pomodoro {session}/{total} démarrée ! Concentrez-vous pendant {duration} minutes 🍅',
			pomoBreak: 'Session {session}/{total} terminée ! Pause de {break} minutes ☕',
			pomoComplete: 'Les {total} sessions Pomodoro sont terminées ! Bon travail ! 🎉',
			pause: 'Minuteur en pause ⏸️',
			resume: 'Minuteur repris ▶️',
			clearList: 'Toutes les tâches ont été effacées',
			clearDone: 'Toutes les tâches terminées ont été effacées',
			clearUser: 'Toutes les tâches de {message} ont été effacées',
		},
		JP: {
			timer: 'フォーカスタイマーが {message} 分に設定されました',
			pomo: 'ポモドーロ セッション {session}/{total} 開始！{duration} 分間集中しましょう 🍅',
			pomoBreak: 'セッション {session}/{total} 完了！{break} 分間の休憩です ☕',
			pomoComplete: '{total} 回のポモドーロ セッションがすべて完了しました！お疲れさまでした 🎉',
			pause: 'タイマーを一時停止しました ⏸️',
			resume: 'タイマーを再開しました ▶️',
			clearList: 'すべてのタスクがクリアされました',
			clearDone: '完了したすべてのタスクがクリアされました',
			clearUser: '{message} のすべてのタスクがクリアされました',
		},
		UA: {
			timer: 'Таймер фокусу встановлено на {message} хвилин',
			pomo: 'Сесію Pomodoro {session}/{total} розпочато! Зосередьтесь на {duration} хвилин 🍅',
			pomoBreak: 'Сесію {session}/{total} завершено! Час для перерви на {break} хвилин ☕',
			pomoComplete: 'Усі {total} сесій Pomodoro завершено! Чудова робота! 🎉',
			pause: 'Таймер призупинено ⏸️',
			resume: 'Таймер відновлено ▶️',
			clearList: 'Усі завдання видалено',
			clearDone: 'Усі виконані завдання видалено',
			clearUser: 'Усі завдання {message} видалено',
		},
		DE: {
			timer: 'Fokus-Timer auf {message} Minuten eingestellt',
			pomo: 'Pomodoro-Sitzung {session}/{total} gestartet! Konzentriere dich {duration} Minuten 🍅',
			pomoBreak: 'Sitzung {session}/{total} abgeschlossen! Zeit für eine {break}-minütige Pause ☕',
			pomoComplete: 'Alle {total} Pomodoro-Sitzungen abgeschlossen! Gute Arbeit! 🎉',
			pause: 'Timer pausiert ⏸️',
			resume: 'Timer fortgesetzt ▶️',
			clearList: 'Alle Aufgaben wurden gelöscht',
			clearDone: 'Alle erledigten Aufgaben wurden gelöscht',
			clearUser: 'Alle Aufgaben von {message} wurden gelöscht',
		},
		PT_BR: {
			timer: 'Temporizador de foco definido para {message} minutos',
			pomo: 'Sessão Pomodoro {session}/{total} iniciada! Foque por {duration} minutos 🍅',
			pomoBreak: 'Sessão {session}/{total} concluída! Hora de uma pausa de {break} minutos ☕',
			pomoComplete: 'Todas as {total} sessões Pomodoro concluídas! Bom trabalho! 🎉',
			pause: 'Temporizador pausado ⏸️',
			resume: 'Temporizador retomado ▶️',
			clearList: 'Todas as tarefas foram removidas',
			clearDone: 'Todas as tarefas concluídas foram removidas',
			clearUser: 'Todas as tarefas de {message} foram removidas',
		},
	},
};
